/* ============================================
   BŌRYKU / RYKU — MOCK DATA LAYER
   ============================================ */

const BORIKU_DATA = {

  vehicles: [
    {
      id: 'tacoma-3g',
      name: 'Toyota Tacoma',
      make: 'Toyota',
      model: 'Tacoma',
      generations: [
        { label: '3rd Gen (2016–2023)', years: [2016,2017,2018,2019,2020,2021,2022,2023] },
        { label: '2nd Gen (2005–2015)', years: [2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015] }
      ],
      trims: ['SR','SR5','TRD Sport','TRD Off-Road','Limited','TRD Pro'],
      icon: '🛻',
      popular: true
    },
    {
      id: '4runner-5g',
      name: 'Toyota 4Runner',
      make: 'Toyota',
      model: '4Runner',
      generations: [
        { label: '5th Gen (2010–2024)', years: [2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024] }
      ],
      trims: ['SR5','TRD Sport','TRD Off-Road','Limited','TRD Pro','Nightshade'],
      icon: '🚙',
      popular: true
    },
    {
      id: 'wrangler-jl',
      name: 'Jeep Wrangler',
      make: 'Jeep',
      model: 'Wrangler JL',
      generations: [
        { label: 'JL (2018–2024)', years: [2018,2019,2020,2021,2022,2023,2024] }
      ],
      trims: ['Sport','Sport S','Sahara','Rubicon','392'],
      icon: '🚙',
      popular: true
    },
    {
      id: 'f150-14g',
      name: 'Ford F-150',
      make: 'Ford',
      model: 'F-150',
      generations: [
        { label: '14th Gen (2021–2024)', years: [2021,2022,2023,2024] },
        { label: '13th Gen (2015–2020)', years: [2015,2016,2017,2018,2019,2020] }
      ],
      trims: ['XL','XLT','Lariat','King Ranch','Platinum','Limited','Raptor'],
      icon: '🛻',
      popular: true
    },
    {
      id: 'gladiator-jt',
      name: 'Jeep Gladiator',
      make: 'Jeep',
      model: 'Gladiator',
      generations: [
        { label: 'JT (2020–2024)', years: [2020,2021,2022,2023,2024] }
      ],
      trims: ['Sport','Sport S','Overland','Rubicon','Mojave'],
      icon: '🛻',
      popular: false
    },
    {
      id: 'bronco-6g',
      name: 'Ford Bronco',
      make: 'Ford',
      model: 'Bronco',
      generations: [
        { label: '6th Gen (2021–2024)', years: [2021,2022,2023,2024] }
      ],
      trims: ['Base','Big Bend','Black Diamond','Outer Banks','Badlands','Wildtrak','Everglades','Raptor'],
      icon: '🚙',
      popular: false
    },
    {
      id: 'tundra-3g',
      name: 'Toyota Tundra',
      make: 'Toyota',
      model: 'Tundra',
      generations: [
        { label: '3rd Gen (2022–2024)', years: [2022,2023,2024] },
        { label: '2nd Gen (2007–2021)', years: [2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021] }
      ],
      trims: ['SR','SR5','Limited','Platinum','1794','TRD Pro','Capstone'],
      icon: '🛻',
      popular: false
    }
  ],

  missionTypes: [
    { id: 'overland', label: 'Overland', desc: 'Long-distance off-road travel', icon: '🗺️' },
    { id: 'overlite', label: 'Overlite', desc: 'Lightweight weekend adventure', icon: '⛺' },
    { id: 'rock-crawl', label: 'Rock Crawling', desc: 'Technical rock obstacles', icon: '🪨' },
    { id: 'desert', label: 'Desert Running', desc: 'High-speed desert terrain', icon: '🏜️' },
    { id: 'snow', label: 'Snow & Ice', desc: 'Winter off-road operations', icon: '❄️' },
    { id: 'daily-driver', label: 'Daily Driver+', desc: 'Practical builds for everyday use', icon: '🏙️' }
  ],

  budgetRanges: [
    { id: 'starter', label: 'Starter', range: '$2,500–$7,500', min: 2500, max: 7500 },
    { id: 'core', label: 'Core Build', range: '$7,500–$15,000', min: 7500, max: 15000 },
    { id: 'serious', label: 'Serious Build', range: '$15,000–$30,000', min: 15000, max: 30000 },
    { id: 'full', label: 'Full Send', range: '$30,000+', min: 30000, max: 75000 }
  ],

  categories: [
    { id: 'roof-racks', label: 'Roof Racks', icon: '▬', count: 12 },
    { id: 'rtt', label: 'Rooftop Tents', icon: '⛺', count: 8 },
    { id: 'suspension', label: 'Suspension', icon: '🔧', count: 14 },
    { id: 'front-bumpers', label: 'Front Bumpers', icon: '🛡️', count: 10 },
    { id: 'rear-bumpers', label: 'Rear Bumpers', icon: '🛡️', count: 8 },
    { id: 'sliders', label: 'Rock Sliders', icon: '⚡', count: 7 },
    { id: 'wheels', label: 'Wheels', icon: '⭕', count: 16 },
    { id: 'tires', label: 'Tires', icon: '🔵', count: 12 },
    { id: 'lighting', label: 'Lighting', icon: '💡', count: 18 },
    { id: 'recovery', label: 'Recovery Gear', icon: '🔗', count: 14 },
    { id: 'storage', label: 'Storage', icon: '📦', count: 10 },
    { id: 'communication', label: 'Communication', icon: '📡', count: 6 }
  ],

  products: [
    /* ---- ROOF RACKS ---- */
    {
      id: 'rr-prinsu-01',
      category: 'roof-racks',
      brand: 'Prinsu',
      name: 'Full Cab Roof Rack',
      model: 'Standard Full Rack',
      price: 849,
      installCost: 150,
      installDifficulty: 'Easy Install',
      popularity: 'Best Seller',
      compatibility: ['tacoma-3g','tacoma-2g'],
      weight: '28 lbs',
      svgLayer: 'roof-rack',
      tags: ['popular', 'bestseller'],
      desc: 'Fully welded full cab roof rack with 3/8" crossbar mounting holes. Wind deflector included.'
    },
    {
      id: 'rr-frontrunner-01',
      category: 'roof-racks',
      brand: 'Front Runner',
      name: 'Slimline II Roof Rack',
      model: 'Low Profile Full Platform',
      price: 1190,
      installCost: 180,
      installDifficulty: 'Easy Install',
      popularity: 'Top Rated',
      compatibility: ['tacoma-3g','4runner-5g','tundra-3g'],
      weight: '34 lbs',
      svgLayer: 'roof-rack',
      tags: ['top-rated', 'premium'],
      desc: 'Modular slimline platform rack system. Compatible with entire Front Runner accessory range.'
    },
    {
      id: 'rr-sherpa-01',
      category: 'roof-racks',
      brand: 'Sherpa Equipment Co.',
      name: 'Crestone Roof Rack',
      model: 'Bolt-On Series',
      price: 749,
      installCost: 120,
      installDifficulty: 'Easy Install',
      popularity: '',
      compatibility: ['tacoma-3g'],
      weight: '22 lbs',
      svgLayer: 'roof-rack',
      tags: [],
      desc: 'Lightweight aluminum bolt-on rack. No drill installation for most applications.'
    },
    {
      id: 'rr-gobi-01',
      category: 'roof-racks',
      brand: 'Gobi',
      name: 'Stealth Roof Rack',
      model: 'Multi-Fan Edition',
      price: 995,
      installCost: 160,
      installDifficulty: 'Pro Install',
      popularity: 'Popular',
      compatibility: ['4runner-5g','wrangler-jl'],
      weight: '38 lbs',
      svgLayer: 'roof-rack',
      tags: ['popular'],
      desc: 'Heavy-duty stealth rack with integrated fan venting slots. Spare tire compatible.'
    },
    {
      id: 'rr-arb-01',
      category: 'roof-racks',
      brand: 'ARB',
      name: 'Base Rack System',
      model: 'Steel Platform',
      price: 1380,
      installCost: 200,
      installDifficulty: 'Pro Install',
      popularity: 'Premium',
      compatibility: ['tacoma-3g','4runner-5g','tundra-3g','f150-14g'],
      weight: '62 lbs',
      svgLayer: 'roof-rack',
      tags: ['premium'],
      desc: 'Heavy-duty steel platform rack with integrated traction board mounts and recovery gear storage.'
    },
    {
      id: 'rr-cbi-01',
      category: 'roof-racks',
      brand: 'CBI Off-Road',
      name: 'T-Series Roof Rack',
      model: '3rd Gen Specific',
      price: 699,
      installCost: 100,
      installDifficulty: 'Easy Install',
      popularity: '',
      compatibility: ['tacoma-3g'],
      weight: '19 lbs',
      svgLayer: 'roof-rack',
      tags: [],
      desc: 'Made in the USA. Low-profile aluminum design with full LED light bar mount cutout.'
    },

    /* ---- ROOFTOP TENTS ---- */
    {
      id: 'rtt-ikamper-01',
      category: 'rtt',
      brand: 'iKamper',
      name: 'Skycamp 3.0',
      model: 'Hard Shell',
      price: 3799,
      installCost: 120,
      installDifficulty: 'Easy Install',
      popularity: 'Best Seller',
      compatibility: ['tacoma-3g','4runner-5g','tundra-3g','f150-14g','bronco-6g'],
      weight: '128 lbs',
      svgLayer: 'rtt',
      tags: ['bestseller', 'popular'],
      desc: 'Premium hard-shell RTT with auto-open feature and 2-second setup. Fits up to 4 adults.'
    },
    {
      id: 'rtt-arb-01',
      category: 'rtt',
      brand: 'ARB',
      name: 'Simpson III',
      model: 'Hard Shell w/ Annex',
      price: 3299,
      installCost: 150,
      installDifficulty: 'Pro Install',
      popularity: 'Top Rated',
      compatibility: ['tacoma-3g','4runner-5g','wrangler-jl','gladiator-jt'],
      weight: '155 lbs',
      svgLayer: 'rtt',
      tags: ['top-rated'],
      desc: 'Fiberglass hard-shell RTT with full-width window and optional annex room attachment.'
    },
    {
      id: 'rtt-roofnest-01',
      category: 'rtt',
      brand: 'Roofnest',
      name: 'Condor Overland',
      model: 'Clamshell Hard Shell',
      price: 2995,
      installCost: 100,
      installDifficulty: 'Easy Install',
      popularity: 'Popular',
      compatibility: ['tacoma-3g','4runner-5g','f150-14g','bronco-6g'],
      weight: '115 lbs',
      svgLayer: 'rtt',
      tags: ['popular'],
      desc: 'Lightweight clamshell RTT with eco-leather interior and built-in fan/ventilation.'
    },
    {
      id: 'rtt-cvt-01',
      category: 'rtt',
      brand: 'CVT',
      name: 'Mt. Rainier Legacy',
      model: 'Soft Shell Double',
      price: 1399,
      installCost: 80,
      installDifficulty: 'Easy Install',
      popularity: '',
      compatibility: ['tacoma-3g','tacoma-2g','4runner-5g','wrangler-jl'],
      weight: '95 lbs',
      svgLayer: 'rtt',
      tags: [],
      desc: 'Classic fold-out soft shell RTT. Durable 280g canvas fabric with foam pad mattress.'
    },
    {
      id: 'rtt-tepui-01',
      category: 'rtt',
      brand: 'Tepui',
      name: 'Explorer Series',
      model: 'Autana Sky',
      price: 2199,
      installCost: 90,
      installDifficulty: 'Easy Install',
      popularity: 'New',
      compatibility: ['tacoma-3g','4runner-5g','tundra-3g'],
      weight: '105 lbs',
      svgLayer: 'rtt',
      tags: ['new'],
      desc: 'Integrated hardshell with 3-layer waterproof cover and extra-long ladders for lifted trucks.'
    },

    /* ---- SUSPENSION ---- */
    {
      id: 'sus-ome-01',
      category: 'suspension',
      brand: 'Old Man Emu (ARB)',
      name: 'Dakar Lift Kit',
      model: '2.5" BP-51 Bypass',
      price: 2890,
      installCost: 650,
      installDifficulty: 'Pro Install',
      popularity: 'Best Seller',
      compatibility: ['tacoma-3g','4runner-5g'],
      weight: '82 lbs',
      svgLayer: 'suspension',
      tags: ['bestseller', 'pro'],
      desc: 'Full 2.5-inch bypass suspension lift with remote reservoirs. Excellent on/off-road performance.'
    },
    {
      id: 'sus-icon-01',
      category: 'suspension',
      brand: 'ICON Vehicle Dynamics',
      name: 'Stage 5 System',
      model: '2.5" CDCV Coilovers',
      price: 4200,
      installCost: 750,
      installDifficulty: 'Pro Install',
      popularity: 'Top Rated',
      compatibility: ['tacoma-3g','tundra-3g','f150-14g'],
      weight: '95 lbs',
      svgLayer: 'suspension',
      tags: ['top-rated', 'premium', 'pro'],
      desc: 'Stage 5 system with CDCV compression damping control. Fully adjustable from the driver seat.'
    },
    {
      id: 'sus-fox-01',
      category: 'suspension',
      brand: 'Fox Racing Shox',
      name: '2.5 Performance Series',
      model: '2" Lift Kit',
      price: 1999,
      installCost: 500,
      installDifficulty: 'Pro Install',
      popularity: 'Popular',
      compatibility: ['tacoma-3g','4runner-5g','wrangler-jl','bronco-6g'],
      weight: '70 lbs',
      svgLayer: 'suspension',
      tags: ['popular', 'pro'],
      desc: 'Fox 2.5 Performance Series shocks with remote reservoirs. Proven race pedigree for the street.'
    },
    {
      id: 'sus-bilstein-01',
      category: 'suspension',
      brand: 'Bilstein',
      name: '5100 Series Lift',
      model: '1.5–2.5" Adjustable',
      price: 1099,
      installCost: 380,
      installDifficulty: 'Easy Install',
      popularity: '',
      compatibility: ['tacoma-3g','tacoma-2g','4runner-5g','f150-14g','tundra-3g'],
      weight: '45 lbs',
      svgLayer: 'suspension',
      tags: [],
      desc: 'Monotube gas-pressure shocks with adjustable ride height. Great entry-level lift kit.'
    },
    {
      id: 'sus-king-01',
      category: 'suspension',
      brand: 'King Shocks',
      name: 'OEM Performance',
      model: '2.5" External Bypass',
      price: 5800,
      installCost: 900,
      installDifficulty: 'Pro Install',
      popularity: 'Premium',
      compatibility: ['tacoma-3g','tundra-3g','f150-14g'],
      weight: '110 lbs',
      svgLayer: 'suspension',
      tags: ['premium', 'pro'],
      desc: 'Race-proven King Shocks with external bypass tubes and remote reservoirs. Built to order.'
    },

    /* ---- FRONT BUMPERS ---- */
    {
      id: 'fb-arb-01',
      category: 'front-bumpers',
      brand: 'ARB',
      name: 'Summit Front Bumper',
      model: 'Steel Winch Ready',
      price: 2150,
      installCost: 350,
      installDifficulty: 'Pro Install',
      popularity: 'Best Seller',
      compatibility: ['tacoma-3g','4runner-5g','tundra-3g'],
      weight: '186 lbs',
      svgLayer: 'front-bumper',
      tags: ['bestseller', 'pro'],
      desc: 'Full-width steel front bumper with integrated winch mount, fog light ports, and D-ring mounts.'
    },
    {
      id: 'fb-cbi-01',
      category: 'front-bumpers',
      brand: 'CBI Off-Road',
      name: 'Baja Front Bumper',
      model: 'Tube Series',
      price: 1295,
      installCost: 280,
      installDifficulty: 'Pro Install',
      popularity: 'Popular',
      compatibility: ['tacoma-3g'],
      weight: '72 lbs',
      svgLayer: 'front-bumper',
      tags: ['popular'],
      desc: 'Lightweight tube bumper design. Maintains OEM fog lights. USA made mild steel.'
    },
    {
      id: 'fb-warn-01',
      category: 'front-bumpers',
      brand: 'Warn',
      name: 'Ascent Front Bumper',
      model: 'Full Width Steel',
      price: 1799,
      installCost: 320,
      installDifficulty: 'Pro Install',
      popularity: '',
      compatibility: ['tacoma-3g','wrangler-jl','gladiator-jt','bronco-6g'],
      weight: '155 lbs',
      svgLayer: 'front-bumper',
      tags: [],
      desc: 'Heavy-duty front bumper with integrated Warn winch plate and skid protection.'
    },
    {
      id: 'fb-road-armor-01',
      category: 'front-bumpers',
      brand: 'Road Armor',
      name: 'Identity Front Bumper',
      model: 'Intimidator Style',
      price: 2650,
      installCost: 400,
      installDifficulty: 'Pro Install',
      popularity: 'Premium',
      compatibility: ['f150-14g','tundra-3g'],
      weight: '198 lbs',
      svgLayer: 'front-bumper',
      tags: ['premium', 'pro'],
      desc: 'Modular pre-runner style bumper with integrated light bars and tire carrier capability.'
    },

    /* ---- REAR BUMPERS ---- */
    {
      id: 'rb-arb-01',
      category: 'rear-bumpers',
      brand: 'ARB',
      name: 'Deluxe Bar Rear Bumper',
      model: 'Steel w/ Tire Carrier',
      price: 2395,
      installCost: 400,
      installDifficulty: 'Pro Install',
      popularity: 'Best Seller',
      compatibility: ['tacoma-3g','4runner-5g'],
      weight: '210 lbs',
      svgLayer: 'rear-bumper',
      tags: ['bestseller', 'pro'],
      desc: 'Heavy-duty rear step bar with integrated swing-out spare tire carrier and recovery points.'
    },
    {
      id: 'rb-cbi-01',
      category: 'rear-bumpers',
      brand: 'CBI Off-Road',
      name: 'Overland Series Rear',
      model: 'Swing Out Carrier',
      price: 1695,
      installCost: 350,
      installDifficulty: 'Pro Install',
      popularity: 'Popular',
      compatibility: ['tacoma-3g'],
      weight: '165 lbs',
      svgLayer: 'rear-bumper',
      tags: ['popular'],
      desc: 'Rear bumper with bolt-on swing-out tire carrier. Integrated Hi-Lift jack mount.'
    },

    /* ---- ROCK SLIDERS ---- */
    {
      id: 'sl-cbi-01',
      category: 'sliders',
      brand: 'CBI Off-Road',
      name: 'Rock Sliders',
      model: 'Step Series',
      price: 695,
      installCost: 180,
      installDifficulty: 'Easy Install',
      popularity: 'Best Seller',
      compatibility: ['tacoma-3g'],
      weight: '52 lbs',
      svgLayer: 'sliders',
      tags: ['bestseller'],
      desc: 'Heavy-duty rock sliders with integrated tube step. Bolt-on installation.'
    },
    {
      id: 'sl-nfab-01',
      category: 'sliders',
      brand: 'N-Fab',
      name: 'Predator Pro Side Steps',
      model: 'Black Textured',
      price: 550,
      installCost: 120,
      installDifficulty: 'Easy Install',
      popularity: 'Popular',
      compatibility: ['tacoma-3g','tundra-3g','f150-14g'],
      weight: '44 lbs',
      svgLayer: 'sliders',
      tags: ['popular'],
      desc: 'Wheel-to-wheel nerf bars with drop steps. UV-protected black powder coat finish.'
    },
    {
      id: 'sl-ome-01',
      category: 'sliders',
      brand: 'Old Man Emu (ARB)',
      name: 'Side Rail Sliders',
      model: 'Bash Plate Combo',
      price: 895,
      installCost: 200,
      installDifficulty: 'Pro Install',
      popularity: '',
      compatibility: ['4runner-5g','wrangler-jl'],
      weight: '68 lbs',
      svgLayer: 'sliders',
      tags: [],
      desc: 'Full-length sliders with integrated rock bash plates. Welded construction for maximum strength.'
    },

    /* ---- WHEELS ---- */
    {
      id: 'wh-method-01',
      category: 'wheels',
      brand: 'Method Race Wheels',
      name: '305 NV Wheel',
      model: '17x8.5 | 6x139.7',
      price: 299,
      installCost: 80,
      installDifficulty: 'Easy Install',
      popularity: 'Best Seller',
      compatibility: ['tacoma-3g','tacoma-2g','4runner-5g','tundra-3g'],
      weight: '24 lbs',
      svgLayer: 'wheels',
      tags: ['bestseller', 'popular'],
      desc: '17x8.5 matte black finish. -12mm offset for aggressive stance. 2,500 lb load rating per wheel.'
    },
    {
      id: 'wh-method-02',
      category: 'wheels',
      brand: 'Method Race Wheels',
      name: '701 Trail Wheel',
      model: '17x8.5 | 5x150',
      price: 345,
      installCost: 80,
      installDifficulty: 'Easy Install',
      popularity: 'Popular',
      compatibility: ['tundra-3g'],
      weight: '26 lbs',
      svgLayer: 'wheels',
      tags: ['popular'],
      desc: 'Designed for truck terrain use. Cast aluminum with matte black powder coat.'
    },
    {
      id: 'wh-kmc-01',
      category: 'wheels',
      brand: 'KMC Wheels',
      name: 'XD811 Rockstar 3',
      model: '17x9 | Multi-Fitment',
      price: 265,
      installCost: 80,
      installDifficulty: 'Easy Install',
      popularity: 'Popular',
      compatibility: ['tacoma-3g','wrangler-jl','bronco-6g','f150-14g'],
      weight: '28 lbs',
      svgLayer: 'wheels',
      tags: ['popular'],
      desc: 'Bold 6-spoke design with gloss black machined finish. -18mm offset.'
    },
    {
      id: 'wh-fuel-01',
      category: 'wheels',
      brand: 'Fuel Off-Road',
      name: 'D595 Triton Beadlock',
      model: '17x9 Beadlock',
      price: 425,
      installCost: 120,
      installDifficulty: 'Pro Install',
      popularity: 'Premium',
      compatibility: ['tacoma-3g','wrangler-jl','gladiator-jt','bronco-6g'],
      weight: '31 lbs',
      svgLayer: 'wheels',
      tags: ['premium', 'pro'],
      desc: 'True beadlock wheel for extreme off-road use. Run at low tire pressure without losing bead.'
    },

    /* ---- TIRES ---- */
    {
      id: 'ti-bfg-01',
      category: 'tires',
      brand: 'BF Goodrich',
      name: 'KO2 All-Terrain',
      model: '285/70R17',
      price: 255,
      installCost: 60,
      installDifficulty: 'Easy Install',
      popularity: 'Best Seller',
      compatibility: ['tacoma-3g','4runner-5g','tundra-3g','wrangler-jl'],
      weight: '50 lbs',
      svgLayer: 'tires',
      tags: ['bestseller', 'popular'],
      desc: 'The most popular all-terrain tire. CoreGard technology protects against sidewall cuts.'
    },
    {
      id: 'ti-falken-01',
      category: 'tires',
      brand: 'Falken Wildpeak',
      name: 'A/T3W',
      model: '285/70R17',
      price: 210,
      installCost: 60,
      installDifficulty: 'Easy Install',
      popularity: 'Top Rated',
      compatibility: ['tacoma-3g','4runner-5g','f150-14g','tundra-3g'],
      weight: '48 lbs',
      svgLayer: 'tires',
      tags: ['top-rated'],
      desc: 'Aggressive A/T tire with 3-peak mountain snowflake rating. Great on/off-road balance.'
    },
    {
      id: 'ti-toyo-01',
      category: 'tires',
      brand: 'Toyo Tires',
      name: 'Open Country M/T',
      model: '35x12.5R17',
      price: 315,
      installCost: 70,
      installDifficulty: 'Easy Install',
      popularity: 'Popular',
      compatibility: ['tacoma-3g','wrangler-jl','gladiator-jt','bronco-6g'],
      weight: '65 lbs',
      svgLayer: 'tires',
      tags: ['popular'],
      desc: 'Aggressive mud terrain tire with Tri-Void lateral grooves for self-cleaning in deep mud.'
    },

    /* ---- LIGHTING ---- */
    {
      id: 'li-baja-01',
      category: 'lighting',
      brand: 'Baja Designs',
      name: 'LP9 Pro Light Pod',
      model: 'Dual LED — Pair',
      price: 890,
      installCost: 180,
      installDifficulty: 'Pro Install',
      popularity: 'Best Seller',
      compatibility: ['tacoma-3g','4runner-5g','wrangler-jl','f150-14g','bronco-6g'],
      weight: '3 lbs',
      svgLayer: 'aux-lights',
      tags: ['bestseller', 'premium'],
      desc: 'Race-proven LP9 pods with 16,000 raw lumens each. IP69K waterproof rating.'
    },
    {
      id: 'li-rigid-01',
      category: 'lighting',
      brand: 'Rigid Industries',
      name: 'E-Series Pro 20"',
      model: 'Light Bar',
      price: 545,
      installCost: 150,
      installDifficulty: 'Pro Install',
      popularity: 'Top Rated',
      compatibility: ['tacoma-3g','4runner-5g','tundra-3g','f150-14g'],
      weight: '4.5 lbs',
      svgLayer: 'lightbar',
      tags: ['top-rated'],
      desc: '20-inch combo beam light bar. 108W total power with 8,800 lumens. Die-cast housing.'
    },
    {
      id: 'li-kc-01',
      category: 'lighting',
      brand: 'KC HiLiTES',
      name: 'FLEX ERA 3',
      model: 'Single Mount',
      price: 399,
      installCost: 130,
      installDifficulty: 'Easy Install',
      popularity: 'Popular',
      compatibility: ['tacoma-3g','4runner-5g','wrangler-jl','bronco-6g'],
      weight: '2.8 lbs',
      svgLayer: 'aux-lights',
      tags: ['popular'],
      desc: 'Versatile beam-shaping light with swappable optic system. Works as spot or spread.'
    },
    {
      id: 'li-oracle-01',
      category: 'lighting',
      brand: 'Oracle Lighting',
      name: 'ColorSHIFT Rock Light Kit',
      model: '8-Piece RGB',
      price: 199,
      installCost: 120,
      installDifficulty: 'Pro Install',
      popularity: '',
      compatibility: ['tacoma-3g','4runner-5g','tundra-3g','wrangler-jl','bronco-6g','f150-14g'],
      weight: '1.2 lbs',
      svgLayer: 'aux-lights',
      tags: [],
      desc: '8-piece RGB rock light kit with Bluetooth app control. 16 million color options.'
    },

    /* ---- RECOVERY ---- */
    {
      id: 're-warn-01',
      category: 'recovery',
      brand: 'Warn',
      name: 'Zeon 10-S Winch',
      model: '10,000 lb Synthetic',
      price: 1249,
      installCost: 200,
      installDifficulty: 'Pro Install',
      popularity: 'Best Seller',
      compatibility: ['tacoma-3g','4runner-5g','tundra-3g','f150-14g','wrangler-jl'],
      weight: '56 lbs',
      svgLayer: null,
      tags: ['bestseller', 'pro'],
      desc: '10,000 lb pulling capacity with synthetic rope. Wireless remote control included.'
    },
    {
      id: 're-maxtrax-01',
      category: 'recovery',
      brand: 'MAXTRAX',
      name: 'MKII Recovery Boards',
      model: '4-Pack Bundle',
      price: 449,
      installCost: 0,
      installDifficulty: 'Easy Install',
      popularity: 'Popular',
      compatibility: ['tacoma-3g','4runner-5g','tundra-3g','f150-14g','wrangler-jl','gladiator-jt','bronco-6g'],
      weight: '14 lbs',
      svgLayer: null,
      tags: ['popular'],
      desc: 'The original vehicle recovery boards. UV-stabilized nylon construction. Australian made.'
    },
    {
      id: 're-factor55-01',
      category: 'recovery',
      brand: 'Factor 55',
      name: 'ProLink Shackle',
      model: 'Flatlink E Bundle',
      price: 285,
      installCost: 0,
      installDifficulty: 'Easy Install',
      popularity: '',
      compatibility: ['tacoma-3g','4runner-5g','tundra-3g','f150-14g','wrangler-jl','gladiator-jt','bronco-6g'],
      weight: '2.5 lbs',
      svgLayer: null,
      tags: [],
      desc: 'Forged aluminum recovery shackle rated to 35,600 lbs. Replaces tow hooks and D-rings.'
    },

    /* ---- STORAGE ---- */
    {
      id: 'st-decked-01',
      category: 'storage',
      brand: 'DECKED',
      name: 'Truck Bed Drawer System',
      model: 'Full Width',
      price: 1199,
      installCost: 120,
      installDifficulty: 'Easy Install',
      popularity: 'Best Seller',
      compatibility: ['tacoma-3g','tundra-3g','f150-14g','gladiator-jt'],
      weight: '135 lbs',
      svgLayer: null,
      tags: ['bestseller'],
      desc: 'Full-width 2-drawer truck bed storage system. 2,000 lb dynamic load rating per drawer.'
    },
    {
      id: 'st-arb-01',
      category: 'storage',
      brand: 'ARB',
      name: 'Zero Fridge/Freezer',
      model: '63 Quart',
      price: 1299,
      installCost: 60,
      installDifficulty: 'Easy Install',
      popularity: 'Popular',
      compatibility: ['tacoma-3g','4runner-5g','tundra-3g','f150-14g','wrangler-jl','bronco-6g'],
      weight: '44 lbs',
      svgLayer: null,
      tags: ['popular'],
      desc: 'Dual-zone 63-quart fridge/freezer with app control. -7°F freezer capability.'
    },

    /* ---- COMMUNICATION ---- */
    {
      id: 'co-midland-01',
      category: 'communication',
      brand: 'Midland',
      name: 'MXT115 MicroMobile GMRS',
      model: '15W GMRS Radio',
      price: 155,
      installCost: 80,
      installDifficulty: 'Easy Install',
      popularity: 'Popular',
      compatibility: ['tacoma-3g','4runner-5g','tundra-3g','f150-14g','wrangler-jl','bronco-6g'],
      weight: '0.8 lbs',
      svgLayer: null,
      tags: ['popular'],
      desc: '15W GMRS mobile radio with 142 privacy codes. Up to 65-mile range in open terrain.'
    },
    {
      id: 'co-garmin-01',
      category: 'communication',
      brand: 'Garmin',
      name: 'inReach Mini 2',
      model: 'Satellite Communicator',
      price: 399,
      installCost: 0,
      installDifficulty: 'Easy Install',
      popularity: 'Top Rated',
      compatibility: ['tacoma-3g','4runner-5g','tundra-3g','f150-14g','wrangler-jl','bronco-6g'],
      weight: '0.2 lbs',
      svgLayer: null,
      tags: ['top-rated'],
      desc: 'Two-way satellite communicator with SOS button. Works 100% off-grid anywhere on Earth.'
    }
  ],

  featuredBuilds: [
    {
      id: 'build-001',
      name: 'TERRA GHOST',
      vehicle: '2022 Toyota Tacoma TRD Pro',
      vehicleId: 'tacoma-3g',
      mission: 'Overland',
      budget: 28500,
      totalCost: 24750,
      owner: 'T. Mercer',
      location: 'Moab, UT',
      parts: ['Prinsu Full Rack', 'iKamper Skycamp 3.0', 'ARB Summit Bumper', 'ICON Stage 5', 'Method 305 NV', 'BFG KO2'],
      tags: ['Overland', 'RTT', 'Fully Built'],
      rating: 4.9,
      saves: 847,
      views: '12.4k',
      accentColor: '#FF551F'
    },
    {
      id: 'build-002',
      name: 'ATLAS BUILD',
      vehicle: '2021 Toyota 4Runner TRD Off-Road',
      vehicleId: '4runner-5g',
      mission: 'Rock Crawling',
      budget: 35000,
      totalCost: 31200,
      owner: 'R. Nakamura',
      location: 'Flagstaff, AZ',
      parts: ['ARB Base Rack', 'Old Man Emu Dakar 2.5"', 'ARB Summit Bumper', 'CBI Sliders', 'Fuel Beadlock', 'Toyo MT'],
      tags: ['Rock', 'Pro Build', 'Armored'],
      rating: 4.8,
      saves: 1203,
      views: '18.7k',
      accentColor: '#FF551F'
    },
    {
      id: 'build-003',
      name: 'SAND TIGER',
      vehicle: '2023 Ford F-150 Raptor',
      vehicleId: 'f150-14g',
      mission: 'Desert Running',
      budget: 22000,
      totalCost: 19800,
      owner: 'J. Reyes',
      location: 'Yuma, AZ',
      parts: ['Fox 2.5 Performance', 'Road Armor Bumper', 'Baja Designs LP9', 'Rigid E-Series 20"', 'Method 701'],
      tags: ['Desert', 'Fast', 'Lighting'],
      rating: 4.7,
      saves: 692,
      views: '9.1k',
      accentColor: '#FF551F'
    },
    {
      id: 'build-004',
      name: 'RUBICON COLD',
      vehicle: '2022 Jeep Wrangler Rubicon JL',
      vehicleId: 'wrangler-jl',
      mission: 'Snow & Ice',
      budget: 18000,
      totalCost: 16400,
      owner: 'A. Caldwell',
      location: 'Bend, OR',
      parts: ['Gobi Stealth Rack', 'Warn Ascent Bumper', 'Bilstein 5100', 'KMC XD811', 'Falken A/T3W'],
      tags: ['Snow', 'Winter', 'Daily Driver'],
      rating: 4.6,
      saves: 455,
      views: '7.3k',
      accentColor: '#FF551F'
    },
    {
      id: 'build-005',
      name: 'MIDNIGHT RUNNER',
      vehicle: '2021 Jeep Gladiator Mojave',
      vehicleId: 'gladiator-jt',
      mission: 'Overland',
      budget: 26000,
      totalCost: 23100,
      owner: 'M. Castillo',
      location: 'Sedona, AZ',
      parts: ['ARB Base Rack', 'CVT RTT', 'ARB Summit Bumper', 'ARB Rear Swing Out', 'Fox 2.5 Performance', 'Toyo AT'],
      tags: ['Overland', 'RTT', 'Trail Ready'],
      rating: 4.7,
      saves: 780,
      views: '11.2k',
      accentColor: '#FF551F'
    },
    {
      id: 'build-006',
      name: 'ALPINE TACTIC',
      vehicle: '2023 Ford Bronco Badlands',
      vehicleId: 'bronco-6g',
      mission: 'Rock Crawling',
      budget: 20000,
      totalCost: 18700,
      owner: 'S. Thompson',
      location: 'Denver, CO',
      parts: ['Warn Ascent Bumper', 'Fox 2.5 Performance', 'Fuel Beadlock', 'Baja Designs LP9', 'DECKED Drawer'],
      tags: ['Rock', 'Bronco', 'Built'],
      rating: 4.9,
      saves: 920,
      views: '14.8k',
      accentColor: '#FF551F'
    }
  ],

  installers: [
    {
      id: 'inst-001',
      name: 'APEX Off-Road Fabrication',
      initials: 'AO',
      location: 'Tempe, AZ',
      distance: '4.2 mi',
      rating: 4.9,
      reviewCount: 148,
      specialties: ['Suspension', 'Fabrication', 'Winches', 'Bumpers'],
      certifications: ['ARB Certified', 'ICON Dealer'],
      since: 2012,
      stats: { builds: 620, brands: 35, avgTime: '3 days' },
      availability: 'Available This Week',
      priceRange: '$$$',
      phone: '(480) 555-0181'
    },
    {
      id: 'inst-002',
      name: 'Terrain Command Outfitters',
      initials: 'TC',
      location: 'Scottsdale, AZ',
      distance: '8.7 mi',
      rating: 4.8,
      reviewCount: 203,
      specialties: ['Rooftop Tents', 'Racks', 'Lighting', 'Electronics'],
      certifications: ['iKamper Dealer', 'Prinsu Certified', 'Rigid Industries'],
      since: 2015,
      stats: { builds: 890, brands: 52, avgTime: '1-2 days' },
      availability: 'Next Available: Mon',
      priceRange: '$$',
      phone: '(480) 555-0249'
    },
    {
      id: 'inst-003',
      name: 'Mesa Motorsports & Fab',
      initials: 'MM',
      location: 'Mesa, AZ',
      distance: '12.1 mi',
      rating: 4.7,
      reviewCount: 94,
      specialties: ['Full Builds', 'Suspension', 'Wheels & Tires'],
      certifications: ['King Shocks Dealer', 'Method Wheels'],
      since: 2018,
      stats: { builds: 310, brands: 28, avgTime: '4-5 days' },
      availability: 'Booking 2 Weeks Out',
      priceRange: '$$$',
      phone: '(480) 555-0392'
    },
    {
      id: 'inst-004',
      name: 'Desert Iron Builds',
      initials: 'DI',
      location: 'Gilbert, AZ',
      distance: '14.5 mi',
      rating: 4.6,
      reviewCount: 67,
      specialties: ['Recovery', 'Communications', 'Lighting'],
      certifications: ['Warn Certified', 'Baja Designs Dealer'],
      since: 2020,
      stats: { builds: 185, brands: 22, avgTime: '2-3 days' },
      availability: 'Available This Week',
      priceRange: '$$',
      phone: '(480) 555-0511'
    },
    {
      id: 'inst-005',
      name: 'Phoenix Overland Co.',
      initials: 'PO',
      location: 'Phoenix, AZ',
      distance: '3.8 mi',
      rating: 5.0,
      reviewCount: 312,
      specialties: ['Full Overland Builds', 'Custom Fabrication', 'Fleet Builds'],
      certifications: ['ARB Certified', 'Front Runner', 'Fox Shocks', 'ICON'],
      since: 2010,
      stats: { builds: 1240, brands: 68, avgTime: '5-7 days' },
      availability: 'Booking 3 Weeks Out',
      priceRange: '$$$$',
      phone: '(602) 555-0105'
    },
    {
      id: 'inst-006',
      name: 'Grit & Steel Offroad',
      initials: 'GS',
      location: 'Chandler, AZ',
      distance: '18.2 mi',
      rating: 4.8,
      reviewCount: 128,
      specialties: ['Budget Builds', 'Tires & Wheels', 'Basic Accessories'],
      certifications: ['BFG Preferred', 'Bilstein Dealer'],
      since: 2016,
      stats: { builds: 450, brands: 31, avgTime: '1 day' },
      availability: 'Available Tomorrow',
      priceRange: '$',
      phone: '(480) 555-0677'
    }
  ],

  brands: [
    { id: 'arb', name: 'ARB', category: 'Full Build', productCount: 42, premium: true, initials: 'ARB' },
    { id: 'icon', name: 'ICON Vehicle Dynamics', category: 'Suspension', productCount: 18, premium: true, initials: 'IC' },
    { id: 'fox', name: 'Fox Racing Shox', category: 'Suspension', productCount: 24, premium: true, initials: 'FOX' },
    { id: 'baja', name: 'Baja Designs', category: 'Lighting', productCount: 31, premium: true, initials: 'BD' },
    { id: 'rigid', name: 'Rigid Industries', category: 'Lighting', productCount: 28, premium: false, initials: 'RI' },
    { id: 'warn', name: 'Warn', category: 'Winches & Recovery', productCount: 19, premium: false, initials: 'WN' },
    { id: 'method', name: 'Method Race Wheels', category: 'Wheels', productCount: 22, premium: true, initials: 'MR' },
    { id: 'bfg', name: 'BF Goodrich', category: 'Tires', productCount: 14, premium: false, initials: 'BFG' },
    { id: 'ikamper', name: 'iKamper', category: 'Rooftop Tents', productCount: 8, premium: true, initials: 'IK' },
    { id: 'prinsu', name: 'Prinsu', category: 'Roof Racks', productCount: 11, premium: false, initials: 'PR' },
    { id: 'frontrunner', name: 'Front Runner', category: 'Racks & Storage', productCount: 38, premium: true, initials: 'FR' },
    { id: 'cbi', name: 'CBI Off-Road', category: 'Armor & Protection', productCount: 16, premium: false, initials: 'CB' },
    { id: 'maxtrax', name: 'MAXTRAX', category: 'Recovery', productCount: 6, premium: false, initials: 'MX' },
    { id: 'decked', name: 'DECKED', category: 'Storage', productCount: 9, premium: false, initials: 'DK' },
    { id: 'king', name: 'King Shocks', category: 'Suspension', productCount: 15, premium: true, initials: 'KG' },
    { id: 'fuel', name: 'Fuel Off-Road', category: 'Wheels', productCount: 20, premium: false, initials: 'FL' }
  ]
};
